// Default categories from Tim's Excel – loaded once on first app start

export const DEFAULT_CATEGORIES = [
  // ── Einnahmen ──────────────────────────────────────────────────────────────
  {
    id: 'gehalt',
    name: 'Gehalt Starlinger',
    type: 'income',
    group: 'Einnahmen',
    icon: 'briefcase',
    color: '#70AD47',
    sort_order: 1,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'sonderzahlungen',
    name: 'Sonderzahlungen',
    type: 'income',
    group: 'Einnahmen',
    icon: 'gift',
    color: '#70AD47',
    sort_order: 2,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'nebenjobs',
    name: 'Nebenjobs / Sonstiges',
    type: 'income',
    group: 'Einnahmen',
    icon: 'plus-circle',
    color: '#70AD47',
    sort_order: 3,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'geschenke-einnahmen',
    name: 'Geschenke / Privates',
    type: 'income',
    group: 'Einnahmen',
    icon: 'heart',
    color: '#70AD47',
    sort_order: 4,
    budget_monthly: null,
    usage_count: 0,
  },

  // ── Wohnen & Fixkosten ─────────────────────────────────────────────────────
  {
    id: 'miete',
    name: 'Miete',
    type: 'expense',
    group: 'Wohnen & Fixkosten',
    icon: 'home',
    color: '#1F4E79',
    sort_order: 10,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'strom',
    name: 'Strom',
    type: 'expense',
    group: 'Wohnen & Fixkosten',
    icon: 'zap',
    color: '#1F4E79',
    sort_order: 11,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'gas',
    name: 'Gas / Heizung',
    type: 'expense',
    group: 'Wohnen & Fixkosten',
    icon: 'flame',
    color: '#1F4E79',
    sort_order: 12,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'internet',
    name: 'Internet & Telefon',
    type: 'expense',
    group: 'Wohnen & Fixkosten',
    icon: 'wifi',
    color: '#1F4E79',
    sort_order: 13,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'handy',
    name: 'Handy-Tarif',
    type: 'expense',
    group: 'Wohnen & Fixkosten',
    icon: 'smartphone',
    color: '#1F4E79',
    sort_order: 14,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'streaming',
    name: 'Streaming',
    type: 'expense',
    group: 'Wohnen & Fixkosten',
    icon: 'play-circle',
    color: '#1F4E79',
    sort_order: 15,
    budget_monthly: null,
    usage_count: 0,
  },

  // ── Mobilität ──────────────────────────────────────────────────────────────
  {
    id: 'benzin',
    name: 'Benzin',
    type: 'expense',
    group: 'Mobilität',
    icon: 'fuel',
    color: '#2E74B5',
    sort_order: 20,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'kfz-versicherung',
    name: 'Kfz-Versicherung',
    type: 'expense',
    group: 'Mobilität',
    icon: 'shield',
    color: '#2E74B5',
    sort_order: 21,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'kfz-service',
    name: 'Kfz-Steuer / Service',
    type: 'expense',
    group: 'Mobilität',
    icon: 'wrench',
    color: '#2E74B5',
    sort_order: 22,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'oeffis',
    name: 'Öffis / Parken',
    type: 'expense',
    group: 'Mobilität',
    icon: 'map-pin',
    color: '#2E74B5',
    sort_order: 23,
    budget_monthly: null,
    usage_count: 0,
  },

  // ── Versicherungen ─────────────────────────────────────────────────────────
  {
    id: 'krankenversicherung',
    name: 'Krankenversicherung',
    type: 'expense',
    group: 'Versicherungen',
    icon: 'heart-pulse',
    color: '#833C00',
    sort_order: 30,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'unfallversicherung',
    name: 'Unfallversicherung',
    type: 'expense',
    group: 'Versicherungen',
    icon: 'shield-check',
    color: '#833C00',
    sort_order: 31,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'haushaltsversicherung',
    name: 'Haushalts-/Haftpflicht',
    type: 'expense',
    group: 'Versicherungen',
    icon: 'house',
    color: '#833C00',
    sort_order: 32,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'rechtsschutz',
    name: 'Rechtsschutz',
    type: 'expense',
    group: 'Versicherungen',
    icon: 'scale',
    color: '#833C00',
    sort_order: 33,
    budget_monthly: null,
    usage_count: 0,
  },

  // ── Lebenshaltung ──────────────────────────────────────────────────────────
  {
    id: 'lebensmittel',
    name: 'Lebensmittel & Drogerie',
    type: 'expense',
    group: 'Lebenshaltung',
    icon: 'shopping-cart',
    color: '#375623',
    sort_order: 40,
    budget_monthly: 600,
    usage_count: 0,
  },
  {
    id: 'loui',
    name: 'Loui (Kater)',
    type: 'expense',
    group: 'Lebenshaltung',
    icon: 'cat',
    color: '#375623',
    sort_order: 41,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'aquaristik',
    name: 'Aquaristik',
    type: 'expense',
    group: 'Lebenshaltung',
    icon: 'fish',
    color: '#375623',
    sort_order: 42,
    budget_monthly: null,
    usage_count: 0,
  },

  // ── Gesundheit & Sport ─────────────────────────────────────────────────────
  {
    id: 'supplements',
    name: 'Supplements',
    type: 'expense',
    group: 'Gesundheit & Sport',
    icon: 'pill',
    color: '#7030A0',
    sort_order: 50,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'apotheke',
    name: 'Apotheke / Arzt',
    type: 'expense',
    group: 'Gesundheit & Sport',
    icon: 'stethoscope',
    color: '#7030A0',
    sort_order: 51,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'sport',
    name: 'Home-Gym / Sport',
    type: 'expense',
    group: 'Gesundheit & Sport',
    icon: 'dumbbell',
    color: '#7030A0',
    sort_order: 52,
    budget_monthly: null,
    usage_count: 0,
  },

  // ── Bildung & Software ─────────────────────────────────────────────────────
  {
    id: 'berufsreife',
    name: 'Berufsreifeprüfung',
    type: 'expense',
    group: 'Bildung & Software',
    icon: 'graduation-cap',
    color: '#C55A11',
    sort_order: 60,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'software-abos',
    name: 'Software-Abos',
    type: 'expense',
    group: 'Bildung & Software',
    icon: 'laptop',
    color: '#C55A11',
    sort_order: 61,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'buecher',
    name: 'Bücher / Hörbücher',
    type: 'expense',
    group: 'Bildung & Software',
    icon: 'book-open',
    color: '#C55A11',
    sort_order: 62,
    budget_monthly: null,
    usage_count: 0,
  },

  // ── Freizeit & Sonstiges ───────────────────────────────────────────────────
  {
    id: 'restaurant',
    name: 'Restaurant / Essen',
    type: 'expense',
    group: 'Freizeit & Sonstiges',
    icon: 'utensils',
    color: '#4472C4',
    sort_order: 70,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'reisen',
    name: 'Reisen / Urlaub',
    type: 'expense',
    group: 'Freizeit & Sonstiges',
    icon: 'plane',
    color: '#4472C4',
    sort_order: 71,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'hobbys',
    name: 'Hobbys / Fotografie',
    type: 'expense',
    group: 'Freizeit & Sonstiges',
    icon: 'camera',
    color: '#4472C4',
    sort_order: 72,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'geschenke',
    name: 'Geschenke',
    type: 'expense',
    group: 'Freizeit & Sonstiges',
    icon: 'gift',
    color: '#4472C4',
    sort_order: 73,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'kleidung',
    name: 'Kleidung / Shopping',
    type: 'expense',
    group: 'Freizeit & Sonstiges',
    icon: 'shopping-bag',
    color: '#4472C4',
    sort_order: 74,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'bargeld',
    name: 'Bargeldabhebungen',
    type: 'expense',
    group: 'Freizeit & Sonstiges',
    icon: 'banknote',
    color: '#4472C4',
    sort_order: 75,
    budget_monthly: null,
    usage_count: 0,
  },
  {
    id: 'sonstiges',
    name: 'Sonstiges',
    type: 'expense',
    group: 'Freizeit & Sonstiges',
    icon: 'circle-ellipsis',
    color: '#4472C4',
    sort_order: 76,
    budget_monthly: null,
    usage_count: 0,
  },
]

export const DEFAULT_SETTINGS = [
  { key: 'currency',       value: 'EUR' },
  { key: 'user_name',      value: 'Tim' },
  { key: 'monthly_income', value: 2400 },
  { key: 'theme',          value: 'auto' },
  { key: 'seeded',         value: true },   // checked to avoid re-seeding
]
